### ISSUE TITLE
Retrieve file statistics from within store

### ISSUE THREAD

**Issue by davidstyers** [ianepperson/filestorage#13]
## Thank You
First, let me say thank you for creating this library. The documentation is excellent and It is exactly what I was looking for. I'd be happy to contribute to the project if that is possible.

## Enhancment Idea
It would be nice to have an interface from within the library to access file-related statistics such as size, last accessed time, etc. A good [example](https://github.com/django/django/blob/main/django/core/files/storage.py) of this is the base file storage system for django.

The most intuitive place to house these properties would be on the `FileItem` object and instead of returning `item.filename` from the file handler's `_save` methods, we could return the file object itself.

The main disadvantage of this method is that some refactoring would need to happen to implement it. Currently, `FileItem` is only aware of its location on the filesystem relative to the base path passed to the file handlers. This would prohibit any `os` related operations that require absolute paths. Another disadvantage would be the need to implement specific `FileItem` classes for each handler.

Another way to go about implementing this is to house it on the various file handlers as the pieces of the puzzle are already there. I would contend that this way is slightly less intuitive but much easier to implement.

I'd be happy to work on this enhancement, but I'd like to receive some input on the best course of action.

**Comment by ianepperson** [comment]
Thanks for you kind words. 

What is the use-case for this enhancement? Would this only be for inspection after the file is saved or for other times as well (similar to checking if the file exists)?

I suspect that some statistics are not going to be available depending on the handler.

**Comment by davidstyers** [comment]
The main use-case for this enhancement would be to allow sorting/filtering of files saved to storage based on the file statistics. It would also be useful for inspection like you mention.

I think two methods of allowing users to access the statistics should exist. The first should be an object returned on each save. The second should behave similarly to the exists method. Given a file-name return the statistics in the same fashion as in the first method.

I do share your concern that there is a possibility of not having 100% availability across all handlers. Perhaps just raise a `NotImplementedError` on handlers lacking the ability until we can do better?

**Comment by davidstyers** [comment]
Alright, so I had some time to implement some of the proposed functionality. I closely modeled it after the exists method and use is identical. I only have implemented it in the `LocalFileHandler` and  `AsyncLocalFileHandler` file handlers. Once I implement it in the `S3Handler` , `DummyHandler`, and `AsyncDummyHandler` I will update the tests to cover it. Below is a sample script displaying the functionality.

```python
import urllib

from filestorage import store
from filestorage.handlers import LocalFileHandler

store.handler = LocalFileHandler('/Users/davidstyers/imagination')
store.finalize_config()

uri: str = 'https://storage.googleapis.com/avoco-dev/images/daniel-stone-28LH9sPSk98-unsplash.jpg'
remote: bytes = urllib.request.urlopen(uri).read()

filename: str = store.save_data('test.jpg', remote)

# Returns size in bytes
print('Size of {}:'.format(filename), store.size(filename))
# Returns datetime.date
print('Last accessed time of {}:'.format(filename), store.get_accessed_time(filename))
print('Creation time of {}:'.format(filename), store.get_creation_time(filename))
print('Time of last modification for {}:'.format(filename), store.get_modified_time(filename))
```

```
/Users/davidstyers/PycharmProjects/filestorage/venv/bin/python /Users/davidstyers/PycharmProjects/filestorage/test.py
Size of test-19.jpg: 6845105
Last accessed time of test-19.jpg: 2021-03-11
Creation time of test-19.jpg: 2021-03-11
Time of last modification for test-19.jpg: 2021-03-11

Process finished with exit code 0
```

**Comment by ianepperson** [comment]
Looking pretty good.

This project is young enough that changing the signature of the save methods with a minor version bump is not totally unreasonable - `v0.1.0`. That would clear the way to add that metadata to the FileItem object and just return that for all save calls. For consistency, the same FileItem could then be returned for a single `get_metadata` call.

**Comment by ianepperson** [comment]
Started a new job shortly before you published the PR; sorry I haven't been able to get to it until now. I'll give it a review.

**Comment by davidstyers** [comment]
#15 closes this.
